#服务器配置
server:
  port: 9000
  servlet:
    content-path: /book

#数据库相关配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/book?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #解析resources/静态资源
    mvc:
      static-path-pattern: /**

#mybatis plus配置
mybatis-plus:
  #如果放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  #如果放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-location: classpath*:mapper/*/Mapper.xml
  #实体扫描 多个package用逗号或者分号分隔
  typeAliasesPackage: com.book.bookshop.entity
  global-config:
  #主键类型 0："数据库id自增“ 1:"用户输入id" 2:"全局唯一id(数字类型id)"  3:"全局唯一id uuid"
  id-type: 0
  #字段策略 0：”忽略判断“ 1:"非null判断" 2：”非空判断“
  field-strategy: 0
  #驼峰下划线转换
  logic-delete-value: 1
  logic-not-delete-value: 0
  #自定义填充策略接口实现
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #配置返回数据库
    cache-enabled: true

